
minio:
  endpoint: "localhost:9100"
  accessKeyID: "minioadmin"
  secretAccessKey: "minioadmin"
  useSSL: false
  bucket: "product-images"

database:
  host: "localhost"
  user: "admin"
  password: "admin123"
  dbname: "ecommerce"
  port: "5432"
  sslmode: "disable"

server:
  port: ":8080"

cors:
  allowOrigins: ["http://localhost:3000"]
